version: 1
APPLICATION_NAME: translator
MAX_LENGTH: 250
DEFAULT_PRETRAINED_HFACE_MODEL_FILEPATH: opus-mt-en-ru
DEFAULT_HF_NAME_MODEL_FILEPATH: Helsinki-NLP/opus-mt-en-ru
DEFAULT_PRETRAINED_USER_MODEL_FILEPATH: ./data/stored-opus-mt-en-ru
DEFAULT_DB_FILEPATH: ../../data/stored-opus-mt-en-ru
INPUT_TEXT: I love to listen music.
